sudo: required
jobs:
  include:
  - stage: build
    os: linux
    jdk: oraclejdk8
    language: generic
    before_install:
    - wget https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz
    - tar -xzvf protobuf-cpp-3.6.1.tar.gz
    - pushd protobuf-3.6.1 && ./configure --disable-shared && make && sudo make install
      && popd
    script: "./ci/travis.sh"
  - stage: deploy
    os: osx
    osx_image: xcode9.4
    language: generic
    env:
    - HOMEBREW_TEMP="/tmp"
    - LDFLAGS="/usr/local/lib/libprotobuf.a /usr/local/lib/libprotoc.a"
    before_install:
    - brew update
    - EDITOR="sed -i '' 's/system \".\/configure\",/system \".\/configure\", \"--disable-shared\",/g'"
      brew edit protobuf
    - brew install protobuf
    script: "./ci/travis.sh"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2"
env:
  global:
  - secure: "ErthuwJHqk8MPlGQcwaSV1mk6DI1z6YHg+XnNUE9yx/EXUqVMyazu5u9VqlZhMMQQm6II8Y8oBF1uK4JdNVKa44xCt8OM3d/HbG5WhYyigNuKaOgK19FGfA7hciY4gzcMsix/lOryqu8JlYqABAIJFwZIJFtnEdylxUO46/PLP01TOHVOrnaUXpTNm6esaXfmgv1ToQCtwALSgo/xy2KYFA6vpzcTYnMii9eMaOZdy3162t8M6equ2WHhqiKvxCX1+M8D76/WoRF1v45dekAV3UKSBf5b3UcK1W1V/NxtwMufD7tXLGxDsBo2JWQOLjx+AyiKGwhVkZBbvfECDKKjq3x5NMjvjqleprYNEKQYibCNvhXVpZPZgKt899RHOXMjt+fr+iq1aHpHU98iFWXyp+MgYbe9Fez/xcWDH9rri+LKsCgZd1PtpDjTjUsZWesAsXYQatTGOZ0w0cOkURbVhUKltnf/AzuhOlj3XqJmO30vKiBhtwzyfvrURc+0GqWlRoU0C1qskmtmI10PJRR1Qv3eMKvvi6XIQfit9J01V/0sJ+WoG6980hJy0N421qr1+LNg3WmDGtMp6UyoAvjUbDFaW3xzGdbsNmLzWqfaFY1kM7ry6WaVVbGEYz0uHKEvMnqLrM3t18qO4wQsaskGCYEaYSmFp4oMT4pDRgCzvU="
  - secure: "sQYup+Bn5NeIKRa1EWMcgWyfP4kHmD5WZ0slTIjZjGRBqqAR7SdRv1XklkEoUE2BXKxEmhKn5bPA3itmn0ix3N4y9km0q9DRQ0RJF+MFJcSg0CYpSlfjGUEUGoIdYQjreZ+AETAyniLGDVE28tWBQ+GliwfKViiE0LESDihfcqUe/7lcDuc/UMP9h7ecazLjwCmmVNYM94ZfTVoPrbC3Jdtb1sPd65/yZPj7pgBzk/vh82E5tmo0JYr81Rq8CKiYoQ2W7qiTmKL/X33mVxvC9lRRNoqgfAyofgnv5zMbvj1krCcKrkuOJ+A/wTOnkZ1MEL/YK0ilNw0g9oxY0MRXEq9jvms4M2bvGyj0jdKB+ctsXMf9l7ZvWdj1kTEHguQxpjg6hhxrwjRwKk5y0LPJFi3Nqxet00+aB2Wqg1AJ5KwBZ9s2e6nhfAOMnWFVct8mxnFfb/8cu1XfyET5ABBK7PozpcY8VQUVqpoSheKuGdFYRXXgA4o42t+Uxt8G/XX5TRJpaD2FtPa9YwtsrCx6HtCEVetSFZ6X0JeHPdzLBn3XTqyPBoc4bD28VFnEs1NKj+Sbj09sDKH93HQ+PafcJnFiPC7Pdk7NedHCqmEXtppvA+L4pL0V9zDNn93pKLgXsCovcrX7nCnfWk2IjGnDMgZaxWPnW0r0AWsl0BwbqjM="
  - secure: "eV4F5Jp3n8Qi79ATwAUvQdhhZzg/jxKVpTe1ovF0paSWtETe5Whuqb+52nLF4um8NrXDLuTM2Ms12o2rUThaqnEgKWR9HSgwXaBNyYs1zWL3J5+nhrX4/jMKtZ+VY3pH+Sk5KiDgf/jModLrXk6k7uN330PKA3hVLlzA0qc+4QXtnwZNZOQ9sjQsScVxAJ6hBJ8TpUZy4ragg07LTa87p679YFXmsClIQcLdY2eTAIXgNuv0HAe1Eyog3Q5m/ObOdQD0fO3M9Qj9QHWWeh6Rc7dcDA8Nvd6peN+dLaG7DK7Gj+lLyx3K6iXrnHzBHHg1sKKcMeejxxD/0d/auzaqP2ORudSYrblo26AU9fHEUKkdcGS0m5NwOYF9slB1U8KXbIFPPNT+W48h8OgTKPErDvnliujirPBpF9pAC8vRhRORMMbKWQIr14HrxhJ9EBhfJ6iDVBM+xEjVzAOxjRuXia8o5Bzo3rmQwDO+Wvb1bJOZ0u7gPwNkMJF7Nj7ScEx1JLaw2RW1/xhQADxoh74NnNr3XJlicoyLZx+mDNOu0wkW0Q/F04FDlCy78VhSMgoiGPNWDtrjCWWFUhSSCbZFL5sjqFXjz24v0raqKqT12oOUwX9ueeIb0gQsMVj8zSnb7F7oZJpbKaPdofS5eEuNMSKzoJ7Imx5mkryMoL0Czic="
  - secure: "re/ISO0n8AqNiM3IuAIJ6toh6HCx7pCZk55FXGPfAYxUOy4qmcLRKyfjW1WwfkHhEaVbr9SnNK0KgUEmG61ueBzRTXh/LQc2bKd1aTR4Q/wocUKd7h5SmASf//nqh1AXicgvPxi+NJxHhmalceNfDwxHlgUdYPvUsWu0WBCxE9DZQMZe6wh7zmWBhlfHA1s+ijdmtx6BlUmR9USx5B0XVZtbd+LA0dNqLiy+WOVAmegr4IzDDFDFEPyKTjEiiztL2b5ohti8vofxpbf4V7N5Ho2l5vUn8+b4IdH3TuPw4a91g9sN+WEJg/7Wm0TbU7WqNanQAXFyfPvPrP4GNZpo7qEr8eDTnI5VvyQrYKOxr00HNF5DxTlysHdCa3oyvNTYZJYgTSK1mGHQHfGrPMqhVNyFSrP5XnKFZ3mVf7lrm+kosZqE2DteSaPXUF4Bjx3CY50qxifxi6i0KH4WsfnOP8LUZsvx/PUBf3Grw/rxQjtW3stRCUbeBnhfDH4VQJvawPcqx5A26SLZelkoq2Q3e9nf5jf9/ISBhnE5YnixsVfir9NL/Y5CEPK9DvWXaMCiJzro5TFnUSVPkmG/AC1y05Ci961ICxSgK7JmnbmGRl8yeoJE0pWK4zc3ySl5to9yGSvSeiIpPMiQ2Tio2gkSRpAAPrCjBQjBF3Z0ywovowk="

